import '../models/product_model.dart';

final List<ProductModel> productSeeds = [
  // ─── IMNONON (Beverages) ───
  ProductModel(
    name: 'Nescafe 3-in-1 Original',
    category: 'Imnonon',
    purchasePrice: 7.00,
    sellingPrice: 10.00,
    quantity: 100,
    image: 'lib/assets/product_images/nescafe_3in1.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Milo Sachet',
    category: 'Imnonon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/milo_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Tang Orange Juice Sachet',
    category: 'Imnonon',
    purchasePrice: 5.00,
    sellingPrice: 7.00,
    quantity: 60,
    image: 'lib/assets/product_images/tang_orange.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Coca-Cola 8oz',
    category: 'Imnonon',
    purchasePrice: 14.00,
    sellingPrice: 18.00,
    quantity: 48,
    image: 'lib/assets/product_images/coke_8oz.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Royal Tru-Orange 8oz',
    category: 'Imnonon',
    purchasePrice: 14.00,
    sellingPrice: 18.00,
    quantity: 48,
    image: 'lib/assets/product_images/royal_8oz.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'C2 Apple Green Tea',
    category: 'Imnonon',
    purchasePrice: 18.00,
    sellingPrice: 25.00,
    quantity: 30,
    image: 'lib/assets/product_images/c2_apple.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Sprite 8oz',
    category: 'Imnonon',
    purchasePrice: 14.00,
    sellingPrice: 18.00,
    quantity: 48,
    image: 'lib/assets/product_images/sprite_8oz.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Nestea Iced Tea Lemon Sachet',
    category: 'Imnonon',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 60,
    image: 'lib/assets/product_images/nestea_lemon.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Kopiko Brown Coffee Sachet',
    category: 'Imnonon',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 80,
    image: 'lib/assets/product_images/kopiko_brown.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Gatorade Blue Bolt 350ml',
    category: 'Imnonon',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 24,
    image: 'lib/assets/product_images/gatorade_blue.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Wilkins Purified Water 500ml',
    category: 'Imnonon',
    purchasePrice: 10.00,
    sellingPrice: 15.00,
    quantity: 48,
    image: 'lib/assets/product_images/wilkins_500ml.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── ALAK (Alcoholic Drinks) ───
  ProductModel(
    name: 'Tanduay Rhum Dark',
    category: 'Alak',
    purchasePrice: 170.00,
    sellingPrice: 200.00,
    quantity: 50,
    image: 'lib/assets/product_images/tanduay_rhum_dark.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Emperador Brandy Original',
    category: 'Alak',
    purchasePrice: 150.00,
    sellingPrice: 180.00,
    quantity: 50,
    image: 'lib/assets/product_images/emperador_brandy_original.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'San Miguel Beer Pale Pilsen',
    category: 'Alak',
    purchasePrice: 45.00,
    sellingPrice: 55.00,
    quantity: 24,
    image: 'lib/assets/product_images/smb_pale.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Red Horse Beer',
    category: 'Alak',
    purchasePrice: 50.00,
    sellingPrice: 60.00,
    quantity: 24,
    image: 'lib/assets/product_images/red_horse.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Ginebra San Miguel Gin',
    category: 'Alak',
    purchasePrice: 140.00,
    sellingPrice: 170.00,
    quantity: 30,
    image: 'lib/assets/product_images/ginebra_san_miguel.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'San Miguel Light Beer',
    category: 'Alak',
    purchasePrice: 45.00,
    sellingPrice: 55.00,
    quantity: 24,
    image: 'lib/assets/product_images/smb_light.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Tanduay Ice Lemon',
    category: 'Alak',
    purchasePrice: 35.00,
    sellingPrice: 45.00,
    quantity: 24,
    image: 'lib/assets/product_images/tanduay_ice_lemon.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── PAGKAON (Food) ───
  ProductModel(
    name: 'Lucky Me Pancit Canton',
    category: 'Pagkaon',
    purchasePrice: 10.00,
    sellingPrice: 14.00,
    quantity: 60,
    image: 'lib/assets/product_images/pancit_canton.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Chippy BBQ',
    category: 'Pagkaon',
    purchasePrice: 10.00,
    sellingPrice: 15.00,
    quantity: 50,
    image: 'lib/assets/product_images/chippy_bbq.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Skyflakes Crackers',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 40,
    image: 'lib/assets/product_images/skyflakes.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Argentina Corned Beef 150g',
    category: 'Pagkaon',
    purchasePrice: 38.00,
    sellingPrice: 48.00,
    quantity: 30,
    image: 'lib/assets/product_images/argentina_corned_beef.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Century Tuna Flakes in Oil 155g',
    category: 'Pagkaon',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 30,
    image: 'lib/assets/product_images/century_tuna.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Ligo Sardines in Tomato Sauce 155g',
    category: 'Pagkaon',
    purchasePrice: 20.00,
    sellingPrice: 28.00,
    quantity: 30,
    image: 'lib/assets/product_images/ligo_sardines.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Knorr Sinigang Mix',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 50,
    image: 'lib/assets/product_images/knorr_sinigang.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Datu Puti Vinegar',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/datu_puti_vinegar.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Datu Puti Soy Sauce',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/datu_puti_soy.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Ajinomoto Seasoning',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/ajinomoto.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Lucky Me Instant Noodles Chicken',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 60,
    image: 'lib/assets/product_images/lucky_me_chicken.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Piattos Cheese 40g',
    category: 'Pagkaon',
    purchasePrice: 12.00,
    sellingPrice: 18.00,
    quantity: 50,
    image: 'lib/assets/product_images/piattos_cheese.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Nova Country Cheddar 22g',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 50,
    image: 'lib/assets/product_images/nova_cheddar.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Monde Butter Cookies',
    category: 'Pagkaon',
    purchasePrice: 15.00,
    sellingPrice: 22.00,
    quantity: 30,
    image: 'lib/assets/product_images/monde_cookies.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Eden Cheese 165g',
    category: 'Pagkaon',
    purchasePrice: 55.00,
    sellingPrice: 70.00,
    quantity: 20,
    image: 'lib/assets/product_images/eden_cheese.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'UFC Banana Ketchup',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/ufc_banana_ketchup.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Maggi Magic Sarap Sachet',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/maggi_magic_sarap.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Bear Brand Powdered Milk Sachet',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/bear_brand.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── PANGLIMPYO (Personal Care & Hygiene) ───
  ProductModel(
    name: 'Safeguard White Soap Bar',
    category: 'Panglimpyo',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 30,
    image: 'lib/assets/product_images/safeguard_soap.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Head & Shoulders Sachet',
    category: 'Panglimpyo',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/head_shoulders.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Colgate Toothpaste 50ml',
    category: 'Panglimpyo',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 20,
    image: 'lib/assets/product_images/colgate_50ml.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Pantene Shampoo Sachet',
    category: 'Panglimpyo',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/pantene_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Dove Soap Bar',
    category: 'Panglimpyo',
    purchasePrice: 38.00,
    sellingPrice: 50.00,
    quantity: 30,
    image: 'lib/assets/product_images/dove_soap.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Rejoice Shampoo Sachet',
    category: 'Panglimpyo',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/rejoice_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Gillette Razor',
    category: 'Panglimpyo',
    purchasePrice: 15.00,
    sellingPrice: 22.00,
    quantity: 30,
    image: 'lib/assets/product_images/gillette_razor.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Whisper Overnight Napkin',
    category: 'Panglimpyo',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 20,
    image: 'lib/assets/product_images/whisper_overnight.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Kotex Regular Napkin',
    category: 'Panglimpyo',
    purchasePrice: 25.00,
    sellingPrice: 35.00,
    quantity: 20,
    image: 'lib/assets/product_images/kotex_regular.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Toothbrush (Colgate)',
    category: 'Panglimpyo',
    purchasePrice: 12.00,
    sellingPrice: 18.00,
    quantity: 30,
    image: 'lib/assets/product_images/toothbrush.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── GAMIT SA PANIMALAY (Household Items) ───
  ProductModel(
    name: 'Ariel Detergent Powder Sachet',
    category: 'Gamit sa Panimalay',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/ariel_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Zonrox Bleach',
    category: 'Gamit sa Panimalay',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 60,
    image: 'lib/assets/product_images/zonrox_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Joy Dishwashing Liquid',
    category: 'Gamit sa Panimalay',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 60,
    image: 'lib/assets/product_images/joy.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Scotch Brite Dishwashing Sponge',
    category: 'Gamit sa Panimalay',
    purchasePrice: 18.00,
    sellingPrice: 25.00,
    quantity: 20,
    image: 'lib/assets/product_images/scotch_brite.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Tide Detergent Powder Sachet',
    category: 'Gamit sa Panimalay',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/tide_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Downy Fabric Conditioner Sachet',
    category: 'Gamit sa Panimalay',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/downy_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Trash Bag Roll (10pcs)',
    category: 'Gamit sa Panimalay',
    purchasePrice: 18.00,
    sellingPrice: 25.00,
    quantity: 30,
    image: 'lib/assets/product_images/trash_bag.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Candle (Pair)',
    category: 'Gamit sa Panimalay',
    purchasePrice: 10.00,
    sellingPrice: 15.00,
    quantity: 40,
    image: 'lib/assets/product_images/candle.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Baygon Aerosol Spray',
    category: 'Gamit sa Panimalay',
    purchasePrice: 80.00,
    sellingPrice: 100.00,
    quantity: 15,
    image: 'lib/assets/product_images/baygon_spray.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── GAMIT SA ESKWELAHAN (School Supplies) ───
  ProductModel(
    name: 'Ballpen Black',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 50,
    image: 'lib/assets/product_images/ballpen_black.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Intermediate Pad Paper',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 20.00,
    sellingPrice: 28.00,
    quantity: 20,
    image: 'lib/assets/product_images/pad_paper.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Pencil No. 2',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 50,
    image: 'lib/assets/product_images/pencil.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Notebook',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 15.00,
    sellingPrice: 22.00,
    quantity: 30,
    image: 'lib/assets/product_images/notebook.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Ballpen Blue',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 50,
    image: 'lib/assets/product_images/ballpen_blue.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Ruler 12 inch',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 30,
    image: 'lib/assets/product_images/ruler.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Scissors (Small)',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 15.00,
    sellingPrice: 22.00,
    quantity: 20,
    image: 'lib/assets/product_images/scissors.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Glue Stick',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 10.00,
    sellingPrice: 15.00,
    quantity: 30,
    image: 'lib/assets/product_images/glue_stick.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── UBAN PA (Others) ───
  ProductModel(
    name: 'Lighter (Disposable)',
    category: 'Uban Pa',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 30,
    image: 'lib/assets/product_images/lighter.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Marlboro Red Cigarette',
    category: 'Uban Pa',
    purchasePrice: 5.00,
    sellingPrice: 7.00,
    quantity: 100,
    image: 'lib/assets/product_images/marlboro_red.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  // NEW
  ProductModel(
    name: 'Philip Morris Menthol Cigarette',
    category: 'Uban Pa',
    purchasePrice: 5.00,
    sellingPrice: 7.00,
    quantity: 100,
    image: 'lib/assets/product_images/philip_morris_menthol.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'AA Battery (2pcs)',
    category: 'Uban Pa',
    purchasePrice: 25.00,
    sellingPrice: 35.00,
    quantity: 20,
    image: 'lib/assets/product_images/aa_battery.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
