import '../models/product_model.dart';

final List<ProductModel> productSeeds = [
  // ─── INMNOMON (Beverages) ───
  ProductModel(
    name: 'Nescafe 3-in-1 Original',
    category: 'Imnonon',
    purchasePrice: 7.00,
    sellingPrice: 10.00,
    quantity: 100,
    image: 'lib/assets/product_images/nescafe_3in1.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Milo Sachet',
    category: 'Imnonon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/milo_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Tang Orange Juice Sachet',
    category: 'Imnonon',
    purchasePrice: 5.00,
    sellingPrice: 7.00,
    quantity: 60,
    image: 'lib/assets/product_images/tang_orange.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Coca-Cola 8oz',
    category: 'Imnonon',
    purchasePrice: 14.00,
    sellingPrice: 18.00,
    quantity: 48,
    image: 'lib/assets/product_images/coke_8oz.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Royal Tru-Orange 8oz',
    category: 'Imnonon',
    purchasePrice: 14.00,
    sellingPrice: 18.00,
    quantity: 48,
    image: 'lib/assets/product_images/royal_8oz.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'C2 Apple Green Tea',
    category: 'Imnonon',
    purchasePrice: 18.00,
    sellingPrice: 25.00,
    quantity: 30,
    image: 'lib/assets/product_images/c2_apple.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── ALAK (Alcoholic Drinks) ───
  ProductModel(
    name: 'Tanduay Rhum Dark',
    category: 'Alak',
    purchasePrice: 170.00,
    sellingPrice: 200.00,
    quantity: 50,
    image: 'lib/assets/product_images/tanduay_rhum_dark.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Emperador Brandy Original',
    category: 'Alak',
    purchasePrice: 150.00,
    sellingPrice: 180.00,
    quantity: 50,
    image: 'lib/assets/product_images/emperador_brandy_original.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'San Miguel Beer Pale Pilsen',
    category: 'Alak',
    purchasePrice: 45.00,
    sellingPrice: 55.00,
    quantity: 24,
    image: 'lib/assets/product_images/smb_pale.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Red Horse Beer',
    category: 'Alak',
    purchasePrice: 50.00,
    sellingPrice: 60.00,
    quantity: 24,
    image: 'lib/assets/product_images/red_horse.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── PAGKAON (Food) ───
  ProductModel(
    name: 'Lucky Me Pancit Canton',
    category: 'Pagkaon',
    purchasePrice: 10.00,
    sellingPrice: 14.00,
    quantity: 60,
    image: 'lib/assets/product_images/pancit_canton.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Chippy BBQ',
    category: 'Pagkaon',
    purchasePrice: 10.00,
    sellingPrice: 15.00,
    quantity: 50,
    image: 'lib/assets/product_images/chippy_bbq.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Skyflakes Crackers',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 40,
    image: 'lib/assets/product_images/skyflakes.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Argentina Corned Beef 150g',
    category: 'Pagkaon',
    purchasePrice: 38.00,
    sellingPrice: 48.00,
    quantity: 30,
    image: 'lib/assets/product_images/argentina_corned_beef.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Century Tuna Flakes in Oil 155g',
    category: 'Pagkaon',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 30,
    image: 'lib/assets/product_images/century_tuna.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Ligo Sardines in Tomato Sauce 155g',
    category: 'Pagkaon',
    purchasePrice: 20.00,
    sellingPrice: 28.00,
    quantity: 30,
    image: 'lib/assets/product_images/ligo_sardines.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Knorr Sinigang Mix',
    category: 'Pagkaon',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 50,
    image: 'lib/assets/product_images/knorr_sinigang.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Datu Puti Vinegar',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/datu_puti_vinegar.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Datu Puti Soy Sauce',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/datu_puti_soy.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Ajinomoto Seasoning',
    category: 'Pagkaon',
    purchasePrice: 2.00,
    sellingPrice: 3.00,
    quantity: 100,
    image: 'lib/assets/product_images/ajinomoto.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── PANGLIMPYO (Personal Care & Hygiene) ───
  ProductModel(
    name: 'Safeguard White Soap Bar',
    category: 'Panglimpyo',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 30,
    image: 'lib/assets/product_images/safeguard_soap.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Head & Shoulders Sachet',
    category: 'Panglimpyo',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/head_shoulders.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Colgate Toothpaste 50ml',
    category: 'Panglimpyo',
    purchasePrice: 28.00,
    sellingPrice: 38.00,
    quantity: 20,
    image: 'lib/assets/product_images/colgate_50ml.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Pantene Shampoo',
    category: 'Panglimpyo',
    purchasePrice: 6.00,
    sellingPrice: 9.00,
    quantity: 60,
    image: 'lib/assets/product_images/pantene_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── GAMIT SA PANIMALAY (Household Items) ───
  ProductModel(
    name: 'Ariel Detergent Powder',
    category: 'Gamit sa Panimalay',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 80,
    image: 'lib/assets/product_images/ariel_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Zonrox Bleach',
    category: 'Gamit sa Panimalay',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 60,
    image: 'lib/assets/product_images/zonrox_sachet.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Joy Dishwashing Liquid',
    category: 'Gamit sa Panimalay',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 60,
    image: 'lib/assets/product_images/joy.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Scotch Brite Dishwashing Sponge',
    category: 'Gamit sa Panimalay',
    purchasePrice: 18.00,
    sellingPrice: 25.00,
    quantity: 20,
    image: 'lib/assets/product_images/scotch_brite.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── GAMIT SA ESKWELAHAN (School Supplies) ───
  ProductModel(
    name: 'Ballpen Black',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 50,
    image: 'lib/assets/product_images/ballpen_black.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Intermediate Pad Paper',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 20.00,
    sellingPrice: 28.00,
    quantity: 20,
    image: 'lib/assets/product_images/pad_paper.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Pencil No. 2',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 5.00,
    sellingPrice: 8.00,
    quantity: 50,
    image: 'lib/assets/product_images/pencil.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Notebook',
    category: 'Gamit sa Eskwelahan',
    purchasePrice: 15.00,
    sellingPrice: 22.00,
    quantity: 30,
    image: 'lib/assets/product_images/notebook.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // ─── UBAN PA (Others) ───
  ProductModel(
    name: 'Lighter (Disposable)',
    category: 'Uban Pa',
    purchasePrice: 8.00,
    sellingPrice: 12.00,
    quantity: 30,
    image: 'lib/assets/product_images/lighter.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProductModel(
    name: 'Marlboro Red Cigarette',
    category: 'Uban Pa',
    purchasePrice: 5.00,
    sellingPrice: 7.00,
    quantity: 100,
    image: 'lib/assets/product_images/marlboro_red.jpg',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
